---
- name: Extract the calculated journal_buffer_timeout from the original broker file
  xml:
    path: "{{ _broker.path }}/{{ _broker.name }}/etc/broker.xml"
    xpath: "/x:configuration/y:core/y:journal-buffer-timeout"
    content: text
    namespaces:
      x: "urn:activemq"
      y: "urn:activemq:core"
  register: xmlresp
  vars:
    _broker.journal_buffer_timeout: "{{ (xmlresp.matches[0] | dict2items)[0].value }}"

- name: "Configure {{ _broker.name }} broker.xml"
  template:
    src: "artemis/etc/broker.xml"
    dest: "{{ _broker.path }}/{{ _broker.name }}/etc/broker.xml"
    backup: yes
  register: template_object
  notify: "restart broker"

- name: "Configure {{ _broker.name }} bootstrap.xml"
  template:
    src: "artemis/etc/bootstrap.xml"
    dest: "{{ _broker.path }}/{{ _broker.name }}/etc/bootstrap.xml"
  notify: "restart broker"

- name: "Ensure ARTEMIS_HOME is correct in artemis.profile"
  lineinfile:
    dest: "{{ _broker.path }}/{{ _broker.name }}/etc/artemis.profile"
    regexp: "^ARTEMIS_HOME"
    line: "ARTEMIS_HOME='{{ _broker.artemis_home }}'"

- name: "Configure {{ _broker.name }} logging.properties"
  template:
    src: "artemis/etc/logging.properties"
    dest: "{{ _broker.path }}/{{ _broker.name }}/etc/logging.properties"
  notify: "restart broker"

- name: "Configure {{ _broker.name }} jolokia-access.xml"
  template:
    src: "artemis/etc/jolokia-access.xml"
    dest: "{{ _broker.path }}/{{ _broker.name }}/etc/jolokia-access.xml"
  notify: "restart broker"
